DROP PACKAGE PK_Usuario;
DROP PACKAGE BODY PK_Usuario;

DROP PACKAGE PK_Tiendas;
DROP PACKAGE BODY PK_Tiendas;

DROP PACKAGE PK_Producto;
DROP PACKAGE BODY PK_Producto;

DROP PACKAGE PK_Orden;
DROP PACKAGE BODY PK_Orden;