--xTablas
DROP TABLE Ordenes CASCADE CONSTRAINTS;
DROP TABLE Productos CASCADE CONSTRAINTS;
DROP TABLE Tiendas CASCADE CONSTRAINTS;
DROP TABLE TiendasProductos CASCADE CONSTRAINTS;
DROP TABLE Calificaciones CASCADE CONSTRAINTS;
DROP TABLE Cupones CASCADE CONSTRAINTS;
DROP TABLE Telefonos CASCADE CONSTRAINTS;
DROP TABLE Clientes CASCADE CONSTRAINTS;
DROP TABLE Direcciones CASCADE CONSTRAINTS;
DROP TABLE Domiciliarios CASCADE CONSTRAINTS;